// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy6Jvhz1x9G0s5MsRJYhVKr3eCLOQ8zy8',
    appId: '1:363704809445:web:33e583afd63948ea09e10c',
    messagingSenderId: '363704809445',
    projectId: 'dhwani-music-app',
    authDomain: 'dhwani-music-app.firebaseapp.com',
    databaseURL: 'https://dhwani-music-app-default-rtdb.firebaseio.com',
    storageBucket: 'dhwani-music-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kbaOMMpgO0uF0ESOrLVXXsprCcM2fNs',
    appId: '1:363704809445:android:b23c808300839fb609e10c',
    messagingSenderId: '363704809445',
    projectId: 'dhwani-music-app',
    databaseURL: 'https://dhwani-music-app-default-rtdb.firebaseio.com',
    storageBucket: 'dhwani-music-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhTYOn84z0_tkxzx4kRl10YLPMxKKZHc',
    appId: '1:363704809445:ios:cfc9ebbcc4b5b43509e10c',
    messagingSenderId: '363704809445',
    projectId: 'dhwani-music-app',
    databaseURL: 'https://dhwani-music-app-default-rtdb.firebaseio.com',
    storageBucket: 'dhwani-music-app.firebasestorage.app',
    iosBundleId: 'com.example.muzikk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhTYOn84z0_tkxzx4kRl10YLPMxKKZHc',
    appId: '1:363704809445:ios:cfc9ebbcc4b5b43509e10c',
    messagingSenderId: '363704809445',
    projectId: 'dhwani-music-app',
    databaseURL: 'https://dhwani-music-app-default-rtdb.firebaseio.com',
    storageBucket: 'dhwani-music-app.firebasestorage.app',
    iosBundleId: 'com.example.muzikk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy6Jvhz1x9G0s5MsRJYhVKr3eCLOQ8zy8',
    appId: '1:363704809445:web:e8419ada96d3738b09e10c',
    messagingSenderId: '363704809445',
    projectId: 'dhwani-music-app',
    authDomain: 'dhwani-music-app.firebaseapp.com',
    databaseURL: 'https://dhwani-music-app-default-rtdb.firebaseio.com',
    storageBucket: 'dhwani-music-app.firebasestorage.app',
  );
}
